// src/app/api/admin/sub-categories/route.js
import { NextResponse } from 'next/server';
import { getToken } from 'next-auth/jwt';
import connectDB from '../../../../lib/mongodb';
import SubCategory from '../../../../models/SubCategory';
import MainCategory from '../../../../models/MainCategory';
import Product from '../../../../models/Product'; // Imported for product association check in DELETE

const secret = process.env.NEXTAUTH_SECRET;

// Helper function for consistent error responses
const handleError = (error, status = 500) => {
  console.error('API Error:', error);
  return NextResponse.json({ success: false, error: error.message || 'Internal Server Error' }, { status });
};

// GET: Fetch all subcategories (optionally filtered by mainCategory ID)
export async function GET(req) {
  try {
    const token = await getToken({ req, secret });
    // IMPORTANT: Allowing any authenticated user (admin or not) to fetch subcategories
    // for display purposes on the public side.
    if (!token) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    const { searchParams } = new URL(req.url);
    const mainCategoryId = searchParams.get('mainCategoryId');

    let query = {};
    if (mainCategoryId) {
      query.mainCategory = mainCategoryId;
    }

    const subCategories = await SubCategory.find(query)
      .populate('mainCategory', 'name slug') // Populate mainCategory to include its name and slug
      .sort({ name: 1 }); // Sort alphabetically by name

    return NextResponse.json({ success: true, subCategories }, { status: 200 });
  } catch (error) {
    return handleError(error, 500);
  }
}

// POST: Create a new subcategory (REQUIRES ADMIN)
export async function POST(req) {
  try {
    const token = await getToken({ req, secret });
    // This action requires admin privileges
    if (!token || !token.isAdmin) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    // Destructure the new 'description' field along with name and mainCategory
    const { name, description, mainCategory: mainCategoryId } = await req.json();

    if (!name || !mainCategoryId) {
      return NextResponse.json({ success: false, error: 'Subcategory name and mainCategory ID are required.' }, { status: 400 });
    }

    // Verify that the associated main category exists
    const existingMainCategory = await MainCategory.findById(mainCategoryId);
    if (!existingMainCategory) {
      return NextResponse.json({ success: false, error: 'Associated Main Category not found.' }, { status: 404 });
    }

    // Check for duplicate subcategory name (unique within its main category is handled by schema index)
    // However, the model schema has `unique: true` for `name` for global uniqueness.
    // Let's keep the more restrictive check for `name` globally unique, if that's the intent.
    // If the intent is unique per mainCategory only, the schema index { name: 1, mainCategory: 1 } handles it.
    // Assuming 'name' unique globally as per previous interactions on subCategorySchema.
    const existingSubCategory = await SubCategory.findOne({ name: new RegExp(`^${name.trim()}$`, 'i') });
    if (existingSubCategory) {
      return NextResponse.json({ success: false, error: `A subcategory with the name "${name}" already exists.` }, { status: 409 });
    }

    const newSubCategory = new SubCategory({
      name: name.trim(),
      description: description ? description.trim() : '', // Assign the new description
      mainCategory: mainCategoryId,
    });

    await newSubCategory.save(); // Slug is generated by pre-save/pre-validate hook in the model

    // Populate mainCategory for the response, so the frontend gets full details
    await newSubCategory.populate('mainCategory', 'name slug');

    return NextResponse.json({ success: true, subCategory: newSubCategory }, { status: 201 });
  } catch (error) {
    if (error.code === 11000) { // Duplicate key error
      return handleError({ message: 'A subcategory with this name already exists.' }, 409);
    }
    if (error.name === 'ValidationError') {
      return handleError(error, 400);
    }
    return handleError(error, 500);
  }
}

// PUT: Update an existing subcategory (REQUIRES ADMIN)
export async function PUT(req) {
  try {
    const token = await getToken({ req, secret });
    // This action requires admin privileges
    if (!token || !token.isAdmin) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    // Destructure the new 'description' field along with other update fields
    const { id, name, description, mainCategory: mainCategoryId } = await req.json();

    if (!id) {
      return NextResponse.json({ success: false, error: 'Subcategory ID is required for update.' }, { status: 400 });
    }
    if (!name && !description && !mainCategoryId) { // Ensure at least one field is provided for update
      return NextResponse.json({ success: false, error: 'No update data provided.' }, { status: 400 });
    }

    const subCategoryToUpdate = await SubCategory.findById(id);
    if (!subCategoryToUpdate) {
      return NextResponse.json({ success: false, error: 'Subcategory not found.' }, { status: 404 });
    }

    // Apply updates only if the corresponding field is provided
    if (name !== undefined) {
      // Check for duplicate name, excluding the current document being updated
      const existingSubCategoryWithName = await SubCategory.findOne({
        name: new RegExp(`^${name.trim()}$`, 'i'),
        _id: { $ne: id },
      });
      if (existingSubCategoryWithName) {
        return NextResponse.json({ success: false, error: `A subcategory with the name "${name}" already exists.` }, { status: 409 });
      }
      subCategoryToUpdate.name = name.trim();
    }
    if (description !== undefined) {
        subCategoryToUpdate.description = description.trim(); // Update the description
    }
    if (mainCategoryId !== undefined) {
      const existingMainCategory = await MainCategory.findById(mainCategoryId);
      if (!existingMainCategory) {
        return NextResponse.json({ success: false, error: 'New associated Main Category not found.' }, { status: 404 });
      }
      subCategoryToUpdate.mainCategory = mainCategoryId;
    }

    await subCategoryToUpdate.save(); // Save to trigger pre-save hooks (like slug generation) and validate

    // Populate mainCategory for the response
    await subCategoryToUpdate.populate('mainCategory', 'name slug');

    return NextResponse.json({ success: true, subCategory: subCategoryToUpdate }, { status: 200 });
  } catch (error) {
    if (error.code === 11000) { // Duplicate key error
      return handleError({ message: 'A subcategory with this name already exists.' }, 409);
    }
    if (error.name === 'ValidationError') {
      return handleError(error, 400);
    }
    return handleError(error, 500);
  }
}

// DELETE: Delete a subcategory (REQUIRES ADMIN)
export async function DELETE(req) {
  try {
    const token = await getToken({ req, secret });
    // This action requires admin privileges
    if (!token || !token.isAdmin) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    const { searchParams } = new URL(req.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json({ success: false, error: 'Subcategory ID is required for deletion.' }, { status: 400 });
    }

    // Check for associated products before deletion
    const associatedProductsCount = await Product.countDocuments({ subCategory: id });
    if (associatedProductsCount > 0) {
      return NextResponse.json({
        success: false,
        error: `Cannot delete subcategory. ${associatedProductsCount} products are still associated with it. Please reassign or delete these products first.`
      }, { status: 409 });
    }

    const deletedSubCategory = await SubCategory.findByIdAndDelete(id);

    if (!deletedSubCategory) {
      return NextResponse.json({ success: false, error: 'Subcategory not found.' }, { status: 404 });
    }

    return NextResponse.json({ success: true, message: 'Subcategory deleted successfully.' }, { status: 200 });
  } catch (error) {
    return handleError(error, 500);
  }
}
